version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "AgahOfficialP@ssword2030"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "51433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U sa -P AgahOfficialP@ssword2030 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agah_web
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Agah_Db;User Id=sa;Password=AgahOfficialP@ssword2030;MultipleActiveResultSets=True;TrustServerCertificate=True
    ports:
      - "8080:8080"